### ISSUE TITLE
Error compiling main program

### ISSUE THREAD

**Issue by P1X3LT0RCH** [elecyb/OSPE#1]
Hello,
I have a problem to compile the main programm and i get errors like:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Couldn't process file Forms\FilterEditorForm.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.	OSPE		
```	
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0415	no suitable constructor exists to convert from "WCHAR [256]" to "std::basic_string<char, std::char_traits<char>, std::allocator<char>>"	OSPEdll	\OSPE-master\DLL\Process.cpp	106	
```

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		A custom tool 'ResXFileCodeGenerator' is associated with file 'Properties\Resources.resx', but the output of the custom tool was not found in the project.  You may try re-running the custom tool by right-clicking on the file in the Solution Explorer and choosing Run Custom Tool.	OSPE			
```

The DLL worked fine.

Thanks in advance.

**Comment by elecyb** [comment]
Hi,

Error 1:
I got those errors when the code is downloaded as a zip from Github, but when cloned using Git I don't get them.
Try: https://stackoverflow.com/questions/51356602/c-sharp-couldnt-process-file-xxx-resx-due-to-its-being-in-the-internet-or-restr
Remember to restart VS before compiling.

Error 2:
Try changing the OSPEdll project charset from Unicode to miltibyte:
OSPEdll > Configuration Properties > General > Character Set > Use Multi-Byte Character Set

Error 3:
Should be fixed now

**Comment by P1X3LT0RCH** [comment]
Thanks for the reply.
Cloning it using Git solved every problem!
