### ISSUE TITLE
OSPE.DLL

### ISSUE THREAD

**Issue by martyybu** [elecyb/OSPE#7]
This is probably a silly question, but when you run the program it asks for "OSPE.DLL" location. Where can I find OSPE.DLL?

**Comment by martyybu** [comment]
Silly me, I just had to build the OSPEdll project. It's all good now

**Comment by sadasianchick** [comment]
Thanks for getting in touch.
I'm going to check this out soon, and report you my feedback :)

Have a great day!

Em qui, 22 de abr de 2021 11:53 AM, martyybu ***@***.***>
escreveu:
